### ISSUE TITLE
项目思路， 或者理解以及有用的资源，在这里分享

### ISSUE THREAD

**Issue by weiweiyi189** [yunzhiclub/gitlabWebhookToGithub#1]

**Comment by weiweiyi189** [comment]
目前想法：

**1. gitlab 配置url, 地址为本项目的地址。使得gitlab的事件发送给我们系统** 

![image](https://user-images.githubusercontent.com/84075857/210963759-fd24cea8-310e-47f3-aedd-8dcefed50609.png)

**2. 系统接受gitlab发送的消息， 并转换为github的事件**

gitlab webhook event api: https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html
githHub  event Api: https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types

**3. 钉钉群建立github机器人， 系统将转换好的事件，向该webHook发送**

![image](https://user-images.githubusercontent.com/84075857/210964823-7c36d010-2e5c-450e-8f07-371af1363c0c.png)

**Comment by limingao48** [comment]
https://github.com/yunzhiclub/dingtalk-gitlab-webhook
可以参考此项目，此项目已经完成了gitLab消息的接收以及转化，只是将其以自定机器人的方式进行推送，将其推送格式改为GitHub形式再去对接Github机器人即可

**Comment by weiweiyi189** [comment]
目前需要优先完成的几类事件有： Push events， Comments， Issues events， Merge request events， Pipeline events

gitlab webhook event：https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#comment-on-an-issue

![image](https://user-images.githubusercontent.com/84075857/210985284-ba33a6a4-efcb-4f48-a352-00bf7c6f8a30.png)

**Comment by weiweiyi189** [comment]
github **push Event** 必填属性   以及 对应的 gitlab属性
地址： 
gitlab： https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#push-events
github:  https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

github push 事件格式**必填**属性以及属性对照表
| github | 类型 | 意思 |  gitlab|  备注| 
| -------- | ------- | ------- | ------- |------- |
| after |  string   |   The SHA of the most recent commit on ref after the push. |  after    |  |
| base_ref |  string or null |    |  ref |  |
| before|  string  |  The SHA of the most recent commit on ref before the push.  |  before| |
| commits|  array of objects | An array of commit objects describing the pushed commits.   |  commits |  子属性中，gitlab数据缺少committer，distinct， tree_id |
| compare |  string  |  URL that shows the changes in this ref update, from the before commit to the after commit.   |  缺失 | |
| created |  boolean|  Whether this push created the ref.  |  缺失 | |
| deleted|  boolean|  Whether this push deleted the ref.  |  缺失 | |
| forced|  boolean|  Whether this push was a force push of the ref. |  缺失 | |
| head_commit |  object or null |  Whether this push was a force push of the ref. |  缺失 | |
| pusher|  object  |  Metaproperties for Git author/committer information. |  缺失，但可以从gitlab 的 user_name等user字段获取 |   |
| ref |  string |  The full git ref that was pushed. Example: refs/heads/main or refs/tags/v3.14.1. |  ref  | |
| repository|  string |  A git repository |  repository | |

**Comment by weiweiyi189** [comment]
github **Issue  Event** 必填属性   以及 对应的 gitlab属性
地址： 
gitlab： https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#issue-events
github:  https://docs.github.com/zh/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=assigned#issues

**github 中 issue 的 aciton 有 16 中 状态** 
![image](https://user-images.githubusercontent.com/84075857/211017416-08e48fc0-535a-405d-bf94-96a668d20be3.png)

**而gitlab 中 只有 4 种**

![image](https://user-images.githubusercontent.com/84075857/211017503-eb3fbbf9-25d7-4cd2-aa02-8deff4f41f89.png)


github push 事件格式**必填**属性以及属性对照表
| github | 类型 | 意思 |  gitlab|  备注| 
| -------- | ------- | ------- | ------- |------- |
| action|  string   |    |  object_attributes.action|  |
| issue|  object |  The issue itself.  |  缺失 |  子属性中，部分字段可以获取，但总体缺失较多，可以使用getbyid获取issue | 
| repository|  string  |  A repository on GitHub.  |  repository| |
| sender|  object | A GitHub user   |  user|    |
| changes |  object | The changes to the issue.  |  changes | github格式中，只有atcion为edited时有该字段   |
| milestone|  object | A collection of related issues and pull requests. |  changes | github格式中，只有atcion为milestone时有该字段，可以通过使用gitlab格式中的 object_attributes.milestone_id 获取  milestone |

**Comment by weiweiyi189** [comment]
经过测试： push Event 的事件， 直接复制 gitlab 的payload信息，作为github的 payload 能够兼容，**钉钉能够成功发送。不需要进行格式转换。**

### **gitlab push event的 payload**

![image](https://user-images.githubusercontent.com/84075857/211143238-7ab4b171-fccc-40a2-8cd8-5611701f2749.png)


### **直接复制gitlab 的 payload，不进行格式转换，直接发送**
（仅加上了X-GitHub-Event 请求头属性）
![image](https://user-images.githubusercontent.com/84075857/211143401-3c6062b8-ac80-4e05-b086-ba60c49f0536.png)

### **钉钉成功接受到消息：** 

缺点： process-evaluation:main 不可以点击，原本的github数据，可以直接点击跳转到仓库。 但是push的分支可以点击。总的来说问题不大
![image](https://user-images.githubusercontent.com/84075857/211143449-5d84bfff-ca19-49c6-b57a-0187dbceb555.png)

**Comment by limingao48** [comment]
经过测试ISSUE创建事件不可以直接使用gitlab的payload，不兼容，并且数据存在冲突。
例：
下面是gitlab对应的issue项，如果仅仅将其名称改为issue也不能正常进行推送，缺少user、assginees、number等等数据。
并且如果将这些缺少的数据加入进来（不存在名称上的冲突）仍然无法正常对接github机器人。因为gitlab此实体中其他数据与github机器人存在冲突，删除后才能正常运行。
```
"object_attributes": {
    "author_id": 4,
    "closed_at": null,
    "confidential": false,
    "created_at": "2023-01-07 10:04:10 UTC",
    "description": "这是内容",
    "discussion_locked": null,
    "due_date": null,
    "id": 507,
    "iid": 2,
    "last_edited_at": null,
    "last_edited_by_id": null,
    "milestone_id": null,
    "moved_to_id": null,
    "duplicated_to_id": null,
    "project_id": 8,
    "relative_position": 513,
    "state_id": 1,
    "time_estimate": 0,
    "title": "测试issue标题",
    "updated_at": "2023-01-07 10:04:10 UTC",
    "updated_by_id": null,
    "weight": null,
    "url": "http://gitlab.mengyunzhi.com:2448/limingao/test/-/issues/2",
    "total_time_spent": 0,
    "time_change": 0,
    "human_total_time_spent": null,
    "human_time_change": null,
    "human_time_estimate": null,
    "assignee_ids": [
      4
    ],
    "assignee_id": 4,
    "labels": [

    ],
    "state": "opened",
    "severity": "unknown"
  },
```
github机器人进行issue推送需要的基本数据：仅对于其中 issue 实体而言
```
 "issue": {
    "body": "这是内容",
    "title": "测试issue标题",
    "url": "http://gitlab.mengyunzhi.com:2448/limingao/test/-/issues/2",
    "state": "open",
    "assignee": null,
    "assignees": [],
    "comments": 0,
    "html_url": "https://github.com/limingao48/financial/issues/9",
    "number": 9
  },
```

**Comment by limingao48** [comment]
github机器人进行issue创建推送所需的数据：
```
{
  "action": "opened",
  "object_kind": "issue",
  "issue": {
    "html_url": "http://gitlab.mengyunzhi.com:2448/limingao/test/-/issues/2",
    "number": 2,
    "title": "issue Title",
    "state": "open",
    "body": "content"
  },
  "repository": {
    "name": "测试项目",
    "description": "",
    "html_url": "http://gitlab.mengyunzhi.com:2448/limingao/test"
  },
  "sender": {
    "login": "limingao48",
    "html_url": "https://github.com/limingao48"
  }
}
```
并且对于任务指派（assignee）虽然github会发出相应请求，但是github机器人并不会推送

**Comment by weiweiyi189** [comment]
经测试 ， **issue_comment事件不兼容**。

github格式需要的基础数据如下

_{
    "issue": {
        "html_url": "http://gitlab.mengyunzhi.com:2448/weiweiyi189/myTestProject/-/issues/1",
        "title": "测试issue",
        "number": 1
    },
    "comment": {
        "body": "这是评论"
    },
    "repository": {
        "name": "测试项目",
        "html_url": "http://gitlab.mengyunzhi.com:2448/weiweiyi189/myTestProject"
    },
    "sender": {
        "login": "weiweiyi189",
        "html_url": "http://gitlab.mengyunzhi.com:2448/weiweiyi189"
    }
}_

并且经过测试， 如果数据多了一些额外的属性，钉钉response会报1001错误。 所以属性最好不要多。

上述大部分数据都能通过gitlab的数据获取，除了sender.html_url字段， gitlab数据中缺少该字段。
缺少该字段的话，github机器人推送的用户名不是蓝色， 到时候看情况而定加不加该字段。

![image](https://user-images.githubusercontent.com/84075857/211187499-364c5bf7-d26b-4411-8e87-aa2c36acd0de.png)

**Comment by weiweiyi189** [comment]
gitlab comment事件 有4中类型， 但是用到的只有两种， 其他两种一次没用到

**所以comment 只用开发两种事件  comment on issue, comment on merge request**

![image](https://user-images.githubusercontent.com/84075857/211193940-b438bed1-1e94-4bd1-9aee-12eb1acff9c6.png)

comment on merge request 格式

_{
    "issue": {
        "html_url": "https://github.com/weiweiyi189/Student-Achievement-Management/pull/21",
        "title": "这是pull request",
        "number": 21,
        "pull_request": {
            "html_url": "https://github.com/weiweiyi189/Student-Achievement-Management/pull/21"
        }
    },
    "comment": {
        "body": "这是普通评论"
    },
    "repository": {
        "name": "Student-Achievement-Management",
        "html_url": "https://github.com/weiweiyi189/Student-Achievement-Management"
    },
    "sender": {
        "login": "weiweiyi189",
        "html_url": "http://gitlab.mengyunzhi.com:2448/weiweiyi189"
    }
}_

**和comment on issue 事件相比，多了一个issue.pull_request属性**, 不添加的话，github机器人会认为是 comment on issue事件

![image](https://user-images.githubusercontent.com/84075857/211194300-42ba10ba-65c6-4508-972c-c6ac471f5641.png)


**这两种事件， 都对应着 github 的 issue_comment 事件**，所以X-GitHub-Event 都用 issue_comment 就行
